[workspace]
authors = ["Nickolas K Freeman <nick.freeman524@gmail.com>"]
channels = ["conda-forge"]
name = "OM-522-Fall-2025"
platforms = ["linux-64", "win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.7,<3.14"
polars = ">=1.33.0,<2"
marimo = ">=0.15.2,<0.16"
tqdm = ">=4.67.1,<5"
ipython = ">=9.5.0,<10"
numpy = ">=2.3.2,<3"
matplotlib = ">=3.10.6,<4"
seaborn = ">=0.13.2,<0.14"
pyarrow = ">=21.0.0,<22"
scikit-learn = ">=1.7.1,<2"
